#!/usr/bin/env python3
"""Verify public Athanor receipt packages in this fork.

The verifier is intentionally small: each package under ``athanor_artifacts``
must provide ``SHA256SUMS`` and any ``receipt.json`` must parse. Replay scripts
remain package-local because they depend on the caller's pinned Yosys/Liberty
paths.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import re
import sys
from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parents[1]
ARTIFACT_ROOT = REPO_ROOT / "athanor_artifacts"
# Split literals so this verifier's own source never contains the forbidden
# strings it scans for. This is a manifest-bound structural backstop; the
# comprehensive committed-tree leak authority is ``export_safety_gate.py``
# (ATH-2960).
FORBIDDEN_EXPORT_STRINGS = (
    "/" + "workdir",
    "athanor-" + "kairos-runall",
    "/" + "home/",
    "azure" + "user",
)


def _sha256(path: Path) -> str:
    h = hashlib.sha256()
    with path.open("rb") as f:
        for chunk in iter(lambda: f.read(1024 * 1024), b""):
            h.update(chunk)
    return h.hexdigest()


def _verify_sums(package: Path) -> list[str]:
    problems: list[str] = []
    sums_path = package / "SHA256SUMS"
    if not sums_path.is_file():
        return [f"{package.relative_to(REPO_ROOT)} missing SHA256SUMS"]
    for lineno, raw in enumerate(sums_path.read_text(encoding="utf-8").splitlines(), 1):
        if not raw.strip():
            continue
        try:
            expected, rel = raw.split(maxsplit=1)
        except ValueError:
            problems.append(f"{sums_path.relative_to(REPO_ROOT)}:{lineno}: malformed line")
            continue
        rel = rel.removeprefix("./")
        target = package / rel
        if not target.is_file():
            problems.append(f"{sums_path.relative_to(REPO_ROOT)}:{lineno}: missing {rel}")
            continue
        got = _sha256(target)
        if got != expected:
            problems.append(
                f"{target.relative_to(REPO_ROOT)} sha256 mismatch: {got} != {expected}"
            )
    return problems


def _verify_receipt_json(package: Path) -> list[str]:
    receipt = package / "receipt.json"
    if not receipt.exists():
        return []
    try:
        json.loads(receipt.read_text(encoding="utf-8"))
    except json.JSONDecodeError as exc:
        return [f"{receipt.relative_to(REPO_ROOT)} JSON parse failed: {exc}"]
    return []


def _manifest_bound_files(package: Path) -> list[Path]:
    """Files the package actually SHIPS: everything in SHA256SUMS, plus the
    manifest and receipt themselves. This deliberately EXCLUDES generated
    working-tree artifacts (e.g. ``*.replay.log``, which embed the caller's
    pinned tool paths) so a verifier run after ``replay.sh`` does not self-trip
    on its own logs, while still fail-closed on every shipped artifact."""
    files: list[Path] = []
    sums_path = package / "SHA256SUMS"
    if sums_path.is_file():
        for raw in sums_path.read_text(encoding="utf-8").splitlines():
            if not raw.strip():
                continue
            parts = raw.split(maxsplit=1)
            if len(parts) == 2:
                files.append(package / parts[1].removeprefix("./"))
    for extra in (sums_path, package / "receipt.json", package / "README.md"):
        if extra not in files:
            files.append(extra)
    return files


def _verify_public_export_clean(package: Path) -> list[str]:
    problems: list[str] = []
    for path in sorted(set(_manifest_bound_files(package))):
        if not path.is_file():
            continue
        try:
            data = path.read_text(encoding="utf-8")
        except UnicodeDecodeError:
            continue
        for forbidden in FORBIDDEN_EXPORT_STRINGS:
            if forbidden in data:
                problems.append(
                    f"{path.relative_to(REPO_ROOT)} contains public-export leak: {forbidden}"
                )
    return problems


# Files generated by RUNNING replay.sh (not committed/shipped). Excluded from
# manifest-completeness so an auditor who has run replay.sh does not self-trip.
_GENERATED_SUFFIXES = (".replay.log",)
_AREA_KEY = re.compile(r"area", re.IGNORECASE)
_CELL_KEY = re.compile(r"cell", re.IGNORECASE)


def _sums_listed(package: Path) -> set[str]:
    """Relative filenames bound by SHA256SUMS (``./`` normalized)."""
    sums_path = package / "SHA256SUMS"
    listed: set[str] = set()
    if sums_path.is_file():
        for raw in sums_path.read_text(encoding="utf-8").splitlines():
            parts = raw.split(maxsplit=1)
            if len(parts) == 2:
                listed.add(parts[1].removeprefix("./"))
    return listed


def _sums_entries(package: Path) -> dict[str, str]:
    """SHA256SUMS as ``relpath -> sha256`` with ``./`` normalized."""
    sums_path = package / "SHA256SUMS"
    entries: dict[str, str] = {}
    if sums_path.is_file():
        for raw in sums_path.read_text(encoding="utf-8").splitlines():
            parts = raw.split(maxsplit=1)
            if len(parts) == 2:
                entries[parts[1].removeprefix("./")] = parts[0]
    return entries


def _sums_path_escapes(package: Path) -> list[str]:
    sums_path = package / "SHA256SUMS"
    if not sums_path.is_file():
        return []
    problems: list[str] = []
    package_root = package.resolve()
    for lineno, raw in enumerate(sums_path.read_text(encoding="utf-8").splitlines(), 1):
        parts = raw.split(maxsplit=1)
        if len(parts) != 2:
            continue
        rel = parts[1].removeprefix("./")
        path = Path(rel)
        if path.is_absolute():
            problems.append(f"{sums_path.relative_to(REPO_ROOT)}:{lineno}: SHA256SUMS path must be relative")
            continue
        target = (package / path).resolve()
        try:
            target.relative_to(package_root)
        except ValueError:
            problems.append(
                f"{sums_path.relative_to(REPO_ROOT)}:{lineno}: SHA256SUMS path escapes package: {rel}"
            )
    return problems


def _verify_manifest_complete(package: Path) -> list[str]:
    """Every committed artifact in the package MUST be bound by SHA256SUMS.
    ``_verify_sums`` checks listed->present (hash match); this checks the
    reverse present->listed, so a file added without rehashing ships UNBOUND
    and is caught rather than silently trusted -- the "SHA256SUMS binds ALL"
    property an auditor relies on."""
    sums_path = package / "SHA256SUMS"
    if not sums_path.is_file():
        return []  # absence already flagged by _verify_sums
    listed = _sums_listed(package)
    problems: list[str] = []
    for path in sorted(package.rglob("*")):
        if not path.is_file():
            continue
        rel = path.relative_to(package).as_posix()
        if rel == "SHA256SUMS" or any(rel.endswith(s) for s in _GENERATED_SUFFIXES):
            continue
        if rel not in listed:
            problems.append(
                f"{path.relative_to(REPO_ROOT)} present but NOT bound by SHA256SUMS "
                f"(unlisted artifact ships unverified)"
            )
    return problems


def _load_json(path: Path) -> tuple[dict[str, object] | None, list[str]]:
    try:
        data = json.loads(path.read_text(encoding="utf-8"))
    except json.JSONDecodeError as exc:
        return None, [f"{path.relative_to(REPO_ROOT)} JSON parse failed: {exc}"]
    if not isinstance(data, dict):
        return None, [f"{path.relative_to(REPO_ROOT)} must contain a JSON object"]
    return data, []


def _verify_replay(package: Path) -> list[str]:
    """A package that ships a receipt.json (a reproducible claim) MUST ship a
    self-checking replay.sh: present and containing at least one ``grep -q``
    assertion, so re-running VALIDATES the claim rather than only producing
    logs an auditor must eyeball."""
    if not (package / "receipt.json").is_file():
        return []
    replay = package / "replay.sh"
    if not replay.is_file():
        return [f"{package.relative_to(REPO_ROOT)} ships receipt.json but no replay.sh"]
    if "grep -q" not in replay.read_text(encoding="utf-8"):
        return [
            f"{replay.relative_to(REPO_ROOT)} has no `grep -q` assertion -- replay "
            f"produces logs but does not self-verify the claimed result"
        ]
    return []


def _customer_ready(receipt: dict[str, object]) -> bool:
    return receipt.get("customer_ready") is True


def _is_metric_packet(receipt: dict[str, object]) -> bool:
    status = str(receipt.get("status", ""))
    metrics = receipt.get("metrics", {})
    metric_axes = set(metrics) if isinstance(metrics, dict) else set()
    return "area_timing_opensta_estimated_power" in status or {"area", "timing", "power"} <= metric_axes


# A customer_ready packet must declare a recognized type via its status. The
# metric family (matched by _is_metric_packet) requires the same-candidate
# binding. The proof/equivalence family makes no PPA optimization claim (its
# generic cell counts are documented non-headline context, not a customer PPA
# claim). Any OTHER customer_ready status is unrecognized and REDs: an unknown
# type could hide an unbound PPA surface under any renamed container or axis, so
# we fail closed on the DECLARED TYPE rather than blocklist a container/axis name
# (a per-name skip just moves the evasion one level up). Adding a customer_ready
# type is a deliberate, reviewed event -- extend this allowlist on purpose.
_RECOGNIZED_NONMETRIC_STATUS_MARKERS = (
    "visible_output_equivalence",
    "visible_output_relation",
)


def _nonempty_string(value: object) -> bool:
    return isinstance(value, str) and bool(value.strip())


def _verify_customer_ready_authority(package: Path, receipt: dict[str, object]) -> list[str]:
    """Customer-ready packets must carry an auditable authority block whose
    candidate hashes are bound by the package SHA manifest. The SDK-side Lean
    validator recomputes theorem liveness; this fork-side leg proves the
    receipt's declared candidate binding points at bytes the package actually
    ships."""
    if not _customer_ready(receipt):
        return []
    rel_receipt = (package / "receipt.json").relative_to(REPO_ROOT)
    authority = receipt.get("lean_authority")
    fallback = receipt.get("lean_fallback")
    has_authority = isinstance(authority, dict)
    has_fallback = isinstance(fallback, dict)
    if has_authority == has_fallback:
        return [
            f"{rel_receipt}: customer_ready must carry exactly one of lean_authority or lean_fallback"
        ]
    block = authority if has_authority else fallback
    assert isinstance(block, dict)
    problems: list[str] = []
    for key in ("reason", "strongest_evidence", "scope_boundary") if has_fallback else ():
        if not _nonempty_string(block.get(key)):
            problems.append(f"{rel_receipt}: lean_fallback missing nonempty {key}")
    binding = block.get("candidate_binding")
    if not isinstance(binding, dict):
        problems.append(f"{rel_receipt}: customer_ready authority block missing candidate_binding")
        return problems
    entries = _sums_entries(package)
    bound_hashes = set(entries.values())
    for key in ("gold_sha256", "gate_sha256"):
        value = binding.get(key)
        if not _nonempty_string(value):
            problems.append(f"{rel_receipt}: candidate_binding missing nonempty {key}")
        elif value not in bound_hashes:
            problems.append(
                f"{rel_receipt}: candidate_binding.{key}={value} is not bound by SHA256SUMS"
            )
    candidate = receipt.get("candidate", {})
    if not isinstance(candidate, dict) or not _nonempty_string(candidate.get("candidate_sha256")):
        problems.append(f"{rel_receipt}: customer_ready authority packet missing candidate.candidate_sha256")
        return problems
    gate = binding.get("gate_sha256")
    if gate != candidate["candidate_sha256"]:
        problems.append(
            f"{rel_receipt}: candidate_binding.gate_sha256={gate} does not match "
            f"candidate.candidate_sha256={candidate['candidate_sha256']}"
        )
    return problems


def _verify_same_candidate_metric_binding(package: Path, receipt: dict[str, object]) -> list[str]:
    if not _customer_ready(receipt):
        return []
    if not _is_metric_packet(receipt):
        # Fail-closed against renamed-container AND renamed-axis evasion. Both
        # evasions dodge _is_metric_packet by dropping the metric status marker;
        # keying the skip off a container or axis NAME (e.g. the literal "metrics"
        # key) just moves the goalpost one level up -- a PPA surface under a
        # renamed container such as receipt["ppa_block"] slips a name-based cure.
        # Instead require the DECLARED TYPE: a customer_ready packet that is neither a
        # recognized metric packet nor a recognized proof/equivalence packet REDs,
        # so an unbound PPA surface cannot hide under any renamed key. A pure
        # gold/gate metric-pair SHAPE check was rejected: it false-reds a real
        # proof packet whose area_receipts.generic_cells carries documented
        # non-headline gold/gate cell counts.
        status = str(receipt.get("status", ""))
        if not any(marker in status for marker in _RECOGNIZED_NONMETRIC_STATUS_MARKERS):
            rel_receipt = (package / "receipt.json").relative_to(REPO_ROOT)
            return [
                f"{rel_receipt}: customer_ready packet has unrecognized status "
                f"{status!r} -- not a recognized metric or proof/equivalence type; a "
                f"customer PPA claim must use a recognized bound packet type "
                f"(fail-closed against renamed-container or renamed-axis evasion)"
            ]
        return []
    rel_receipt = (package / "receipt.json").relative_to(REPO_ROOT)
    binding_path = package / "same_candidate_binding_receipt.json"
    if not binding_path.is_file():
        return [f"{rel_receipt}: customer_ready metric packet missing same_candidate_binding_receipt.json"]
    binding, errors = _load_json(binding_path)
    if errors:
        return errors
    assert binding is not None
    problems: list[str] = []
    rel_binding = binding_path.relative_to(REPO_ROOT)
    receipt_candidate = receipt.get("candidate")
    binding_candidate = binding.get("candidate")
    if not isinstance(receipt_candidate, dict):
        problems.append(f"{rel_receipt}: metric packet missing candidate object")
        return problems
    if not isinstance(binding_candidate, dict):
        problems.append(f"{rel_binding}: missing candidate object")
        return problems
    for key in ("candidate_sha256", "mapped_netlist_sha256", "selected_flow"):
        if not _nonempty_string(receipt_candidate.get(key)):
            problems.append(f"{rel_receipt}: candidate missing nonempty {key}")
        if binding_candidate.get(key) != receipt_candidate.get(key):
            problems.append(
                f"{rel_binding}: candidate.{key}={binding_candidate.get(key)!r} does not match "
                f"receipt candidate.{key}={receipt_candidate.get(key)!r}"
            )
    axes = binding.get("axes")
    if not isinstance(axes, dict):
        return problems + [f"{rel_binding}: missing axes object"]
    entries = _sums_entries(package)
    bound_hashes = set(entries.values())
    mapped_sha = binding_candidate.get("mapped_netlist_sha256")
    if not _nonempty_string(mapped_sha) or mapped_sha not in bound_hashes:
        problems.append(f"{rel_binding}: candidate.mapped_netlist_sha256 is not bound by SHA256SUMS")
    for axis_name in ("area", "timing", "power"):
        axis = axes.get(axis_name)
        if not isinstance(axis, dict):
            problems.append(f"{rel_binding}: missing {axis_name} axis")
            continue
        for key in ("candidate_sha256", "mapped_netlist_sha256", "selected_flow"):
            if axis.get(key) != binding_candidate.get(key):
                problems.append(
                    f"{rel_binding}: {axis_name}.{key}={axis.get(key)!r} does not match "
                    f"candidate.{key}={binding_candidate.get(key)!r}"
                )
        for key in ("instrument", "instrument_version"):
            if not _nonempty_string(axis.get(key)):
                problems.append(f"{rel_binding}: {axis_name} missing nonempty {key}")
        metric = axis.get("metric")
        if not isinstance(metric, dict) or not metric:
            problems.append(f"{rel_binding}: {axis_name} missing metric object")
        negative = axis.get("negative_control")
        if not isinstance(negative, dict):
            problems.append(f"{rel_binding}: {axis_name} missing negative_control")
            continue
        if negative.get("axis_reds") is not True:
            problems.append(f"{rel_binding}: {axis_name}.negative_control.axis_reds must be true")
        if not _nonempty_string(negative.get("regressed_candidate_sha256")):
            problems.append(f"{rel_binding}: {axis_name}.negative_control missing regressed_candidate_sha256")
        elif negative.get("regressed_candidate_sha256") == binding_candidate.get("candidate_sha256"):
            problems.append(
                f"{rel_binding}: {axis_name}.negative_control.regressed_candidate_sha256 "
                "must differ from the accepted candidate_sha256"
            )
        elif negative["regressed_candidate_sha256"] not in entries.values():
            problems.append(
                f"{rel_binding}: {axis_name}.negative_control.regressed_candidate_sha256="
                f"{negative['regressed_candidate_sha256']} is not bound by SHA256SUMS"
            )
        log_ref = negative.get("log_ref")
        if not _nonempty_string(log_ref):
            problems.append(f"{rel_binding}: {axis_name}.negative_control missing log_ref")
        elif str(log_ref).removeprefix("./") not in entries:
            problems.append(
                f"{rel_binding}: {axis_name}.negative_control.log_ref={log_ref!r} "
                "is not bound by SHA256SUMS"
            )
    power_axis = axes.get("power")
    if isinstance(power_axis, dict):
        metric = power_axis.get("metric")
        boundary = metric.get("methodology_boundary") if isinstance(metric, dict) else None
        if not (_nonempty_string(boundary) and "not signoff" in boundary and "not measured workload" in boundary):
            problems.append(
                f"{rel_binding}: power.metric.methodology_boundary must qualify "
                "OpenSTA power as not signoff and not measured workload"
            )
    return problems


def _receipt_area_claims(obj: object, key_path: str = "") -> list[tuple[str, float]]:
    """(key_path, value) for every numeric leaf under a key containing 'area'."""
    out: list[tuple[str, float]] = []
    if isinstance(obj, dict):
        for k, v in obj.items():
            out.extend(_receipt_area_claims(v, f"{key_path}.{k}" if key_path else str(k)))
    elif isinstance(obj, list):
        for i, v in enumerate(obj):
            out.extend(_receipt_area_claims(v, f"{key_path}[{i}]"))
    elif isinstance(obj, (int, float)) and not isinstance(obj, bool):
        # An area value, not a cell COUNT (a count under an area_receipts.* key
        # is not itself an area and is not carried in the synthesis area line).
        if _AREA_KEY.search(key_path) and not _CELL_KEY.search(key_path):
            out.append((key_path, float(obj)))
    return out


def _sha_bound_log_text(package: Path) -> str:
    """Concatenated text of every SHA-bound ``*.log`` in the package -- the
    pinned, hash-verified tool output the receipt's numbers must be PARSED
    FROM. Only SHA256SUMS-listed logs count, so an unbound log cannot launder
    a fabricated number."""
    listed = _sums_listed(package)
    chunks: list[str] = []
    for rel in sorted(listed):
        if rel.endswith(".log"):
            fp = package / rel
            if fp.is_file():
                chunks.append(fp.read_text(encoding="utf-8", errors="ignore"))
    return "\n".join(chunks)


def _verify_receipt_bound_to_logs(package: Path) -> list[str]:
    """Every AREA value the receipt CLAIMS must appear verbatim in a SHA-bound
    pinned log -- the receipt's numbers are PARSED FROM the hash-verified tool
    output, never self-asserted. An inflated/tampered area claim that no pinned
    log reproduces is caught. Correctness-only packets (no area claims) are a
    no-op by construction.

    Scope (structure, not execution): this proves the claimed number is PRESENT
    in a SHA-bound log; it does NOT re-run replay.sh. A forgery that fabricates
    BOTH the receipt value AND a matching, SHA256SUMS-listed log passes here --
    reproducibility ultimately rests on the auditor re-running replay.sh, which
    _verify_replay guarantees exists and self-checks. This gate catches drift,
    casual tampering, and self-certification; full forgery is caught by replay."""
    receipt = package / "receipt.json"
    if not receipt.is_file():
        return []
    try:
        data = json.loads(receipt.read_text(encoding="utf-8"))
    except json.JSONDecodeError:
        return []  # parse failure already flagged by _verify_receipt_json
    claims = _receipt_area_claims(data)
    if not claims:
        return []
    logtext = _sha_bound_log_text(package)
    problems: list[str] = []
    for key_path, value in claims:
        # Match the value at the precisions tool logs emit it (Yosys stat prints
        # 6 decimals; receipts round to 4). Require a decimal-anchored form so a
        # short area cannot spuriously match a longer number's prefix.
        forms = (f"{value:.6f}", f"{value:.4f}", f"{value:.1f}")
        if not any(form in logtext for form in forms):
            problems.append(
                f"{receipt.relative_to(REPO_ROOT)}: area claim {key_path}={value} does "
                f"not appear in any SHA-bound pinned log "
                f"(receipt self-certifies -- not parsed from the bound bytes)"
            )
    return problems


def _gold_gate_numeric_pairs(obj: object, path: str = "") -> list[tuple[str, str, list[str]]]:
    """(location, enclosing-key, [gold/gate numeric keys]) for every nested dict
    that holds BOTH a gold-prefixed and a gate-prefixed numeric value -- the shape
    of a before/after PPA comparison claim."""
    out: list[tuple[str, str, list[str]]] = []
    if isinstance(obj, dict):
        gk = [
            k for k, v in obj.items()
            if k.lower().startswith("gold") and isinstance(v, (int, float)) and not isinstance(v, bool)
        ]
        tk = [
            k for k, v in obj.items()
            if k.lower().startswith("gate") and isinstance(v, (int, float)) and not isinstance(v, bool)
        ]
        if gk and tk:
            parent = path.rsplit(".", 1)[-1] if path else ""
            out.append((path or "<root>", parent, gk + tk))
        for k, v in obj.items():
            out += _gold_gate_numeric_pairs(v, f"{path}.{k}" if path else k)
    elif isinstance(obj, list):
        for i, v in enumerate(obj):
            out += _gold_gate_numeric_pairs(v, f"{path}[{i}]")
    return out


def _verify_proof_packet_no_smuggled_ppa(package: Path, receipt: dict[str, object]) -> list[str]:
    """A customer_ready proof/equivalence packet makes NO PPA optimization claim,
    so it ships no same-candidate binding. Its ONLY legitimate gold/gate numeric
    context is documented non-headline generic cell counts (a ``generic_cells``
    block, whose keys are all cell counts). Any OTHER gold/gate numeric pair -- for
    example PPA-shaped values (footprint / arrival / power) under a renamed
    container while riding a recognized proof status -- is a smuggled PPA claim
    that dodges the metric-packet binding requirement; RED it. This closes the
    recognized-proof-status + renamed-PPA-container evasion while preserving the
    legitimate generic cell-count context on relation packets."""
    if not _customer_ready(receipt):
        return []
    if _is_metric_packet(receipt):
        return []  # bound by _verify_same_candidate_metric_binding
    try:
        rel = (package / "receipt.json").relative_to(REPO_ROOT)
    except ValueError:
        rel = package / "receipt.json"
    problems: list[str] = []
    for loc, parent, keys in _gold_gate_numeric_pairs(receipt):
        # Allowed ONLY as generic cell-count context: the enclosing key is
        # `generic_cells` AND every gold/gate numeric key is itself a cell count.
        if parent == "generic_cells" and all("cell" in k.lower() for k in keys):
            continue
        problems.append(
            f"{rel}: customer_ready proof/equivalence packet presents a gold/gate "
            f"numeric pair at {loc} that is not documented generic cell-count context "
            f"-- a PPA claim must use a recognized bound metric packet (fail-closed "
            f"against renamed-container PPA smuggling under a proof status)"
        )
    return problems


def _verify_customer_ready_receipt(package: Path) -> list[str]:
    receipt_path = package / "receipt.json"
    if not receipt_path.is_file():
        return []
    receipt, errors = _load_json(receipt_path)
    if errors:
        return []  # parse failure already flagged by _verify_receipt_json
    assert receipt is not None
    problems: list[str] = []
    problems.extend(_verify_customer_ready_authority(package, receipt))
    problems.extend(_verify_same_candidate_metric_binding(package, receipt))
    problems.extend(_verify_proof_packet_no_smuggled_ppa(package, receipt))
    return problems


def verify(root: Path = ARTIFACT_ROOT) -> list[str]:
    # A capture-track fork (e.g. riscv-boom-athanor) legitimately has no proof
    # packages yet -- "no artifacts yet" is not a failure. Fail-closed means
    # "missing when expected," which is a separate content check; the export-safety
    # leak scan still runs over the whole committed tree regardless.
    if not root.is_dir():
        return []
    problems: list[str] = []
    # A proof package is a dir carrying a SHA256SUMS or a receipt.json. A capture
    # staging dir (e.g. generated_rtl_capture on the capture-track fork) has
    # neither and is not a proof package -> skip it. A dir with a receipt.json but
    # no SHA256SUMS is still a package and IS flagged by _verify_sums.
    packages = [
        p
        for p in sorted(root.iterdir())
        if p.is_dir() and ((p / "SHA256SUMS").is_file() or (p / "receipt.json").is_file())
    ]
    if not packages:
        return []
    for package in packages:
        problems.extend(_verify_sums(package))
        problems.extend(_sums_path_escapes(package))
        problems.extend(_verify_manifest_complete(package))
        problems.extend(_verify_receipt_json(package))
        problems.extend(_verify_replay(package))
        problems.extend(_verify_receipt_bound_to_logs(package))
        problems.extend(_verify_customer_ready_receipt(package))
        problems.extend(_verify_public_export_clean(package))
    return problems


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--artifact-root",
        type=Path,
        default=ARTIFACT_ROOT,
        help="artifact package root, default: athanor_artifacts",
    )
    args = parser.parse_args(argv)

    problems = verify(args.artifact_root)
    if problems:
        for problem in problems:
            print(f"FAIL: {problem}", file=sys.stderr)
        return 1
    print(f"OK: verified public receipts under {args.artifact_root.relative_to(REPO_ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
