#!/usr/bin/env python3
"""Verify public Athanor receipt packages in this fork.

The verifier is intentionally small: each package under ``athanor_artifacts``
must provide ``SHA256SUMS`` and any ``receipt.json`` must parse. Replay scripts
remain package-local because they depend on the caller's pinned Yosys/Liberty
paths.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import re
import sys
from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parents[1]
ARTIFACT_ROOT = REPO_ROOT / "athanor_artifacts"
# Split literals so this verifier's own source never contains the forbidden
# strings it scans for. This is a manifest-bound structural backstop; the
# comprehensive committed-tree leak authority is ``export_safety_gate.py``
# (ATH-2960).
FORBIDDEN_EXPORT_STRINGS = (
    "/" + "workdir",
    "athanor-" + "kairos-runall",
    "/" + "home/",
    "azure" + "user",
)


def _sha256(path: Path) -> str:
    h = hashlib.sha256()
    with path.open("rb") as f:
        for chunk in iter(lambda: f.read(1024 * 1024), b""):
            h.update(chunk)
    return h.hexdigest()


def _verify_sums(package: Path) -> list[str]:
    problems: list[str] = []
    sums_path = package / "SHA256SUMS"
    if not sums_path.is_file():
        return [f"{package.relative_to(REPO_ROOT)} missing SHA256SUMS"]
    for lineno, raw in enumerate(sums_path.read_text(encoding="utf-8").splitlines(), 1):
        if not raw.strip():
            continue
        try:
            expected, rel = raw.split(maxsplit=1)
        except ValueError:
            problems.append(f"{sums_path.relative_to(REPO_ROOT)}:{lineno}: malformed line")
            continue
        rel = rel.removeprefix("./")
        target = package / rel
        if not target.is_file():
            problems.append(f"{sums_path.relative_to(REPO_ROOT)}:{lineno}: missing {rel}")
            continue
        got = _sha256(target)
        if got != expected:
            problems.append(
                f"{target.relative_to(REPO_ROOT)} sha256 mismatch: {got} != {expected}"
            )
    return problems


def _verify_receipt_json(package: Path) -> list[str]:
    receipt = package / "receipt.json"
    if not receipt.exists():
        return []
    try:
        json.loads(receipt.read_text(encoding="utf-8"))
    except json.JSONDecodeError as exc:
        return [f"{receipt.relative_to(REPO_ROOT)} JSON parse failed: {exc}"]
    return []


def _manifest_bound_files(package: Path) -> list[Path]:
    """Files the package actually SHIPS: everything in SHA256SUMS, plus the
    manifest and receipt themselves. This deliberately EXCLUDES generated
    working-tree artifacts (e.g. ``*.replay.log``, which embed the caller's
    pinned tool paths) so a verifier run after ``replay.sh`` does not self-trip
    on its own logs, while still fail-closed on every shipped artifact."""
    files: list[Path] = []
    sums_path = package / "SHA256SUMS"
    if sums_path.is_file():
        for raw in sums_path.read_text(encoding="utf-8").splitlines():
            if not raw.strip():
                continue
            parts = raw.split(maxsplit=1)
            if len(parts) == 2:
                files.append(package / parts[1].removeprefix("./"))
    for extra in (sums_path, package / "receipt.json", package / "README.md"):
        if extra not in files:
            files.append(extra)
    return files


def _verify_public_export_clean(package: Path) -> list[str]:
    problems: list[str] = []
    for path in sorted(set(_manifest_bound_files(package))):
        if not path.is_file():
            continue
        try:
            data = path.read_text(encoding="utf-8")
        except UnicodeDecodeError:
            continue
        for forbidden in FORBIDDEN_EXPORT_STRINGS:
            if forbidden in data:
                problems.append(
                    f"{path.relative_to(REPO_ROOT)} contains public-export leak: {forbidden}"
                )
    return problems


# Files generated by RUNNING replay.sh (not committed/shipped). Excluded from
# manifest-completeness so an auditor who has run replay.sh does not self-trip.
_GENERATED_SUFFIXES = (".replay.log",)
_AREA_KEY = re.compile(r"area", re.IGNORECASE)
_CELL_KEY = re.compile(r"cell", re.IGNORECASE)


def _sums_listed(package: Path) -> set[str]:
    """Relative filenames bound by SHA256SUMS (``./`` normalized)."""
    sums_path = package / "SHA256SUMS"
    listed: set[str] = set()
    if sums_path.is_file():
        for raw in sums_path.read_text(encoding="utf-8").splitlines():
            parts = raw.split(maxsplit=1)
            if len(parts) == 2:
                listed.add(parts[1].removeprefix("./"))
    return listed


def _verify_manifest_complete(package: Path) -> list[str]:
    """Every committed artifact in the package MUST be bound by SHA256SUMS.
    ``_verify_sums`` checks listed->present (hash match); this checks the
    reverse present->listed, so a file added without rehashing ships UNBOUND
    and is caught rather than silently trusted -- the "SHA256SUMS binds ALL"
    property an auditor relies on."""
    sums_path = package / "SHA256SUMS"
    if not sums_path.is_file():
        return []  # absence already flagged by _verify_sums
    listed = _sums_listed(package)
    problems: list[str] = []
    for path in sorted(package.rglob("*")):
        if not path.is_file():
            continue
        rel = path.relative_to(package).as_posix()
        if rel == "SHA256SUMS" or any(rel.endswith(s) for s in _GENERATED_SUFFIXES):
            continue
        if rel not in listed:
            problems.append(
                f"{path.relative_to(REPO_ROOT)} present but NOT bound by SHA256SUMS "
                f"(unlisted artifact ships unverified)"
            )
    return problems


def _verify_replay(package: Path) -> list[str]:
    """A package that ships a receipt.json (a reproducible claim) MUST ship a
    self-checking replay.sh: present and containing at least one ``grep -q``
    assertion, so re-running VALIDATES the claim rather than only producing
    logs an auditor must eyeball."""
    if not (package / "receipt.json").is_file():
        return []
    replay = package / "replay.sh"
    if not replay.is_file():
        return [f"{package.relative_to(REPO_ROOT)} ships receipt.json but no replay.sh"]
    if "grep -q" not in replay.read_text(encoding="utf-8"):
        return [
            f"{replay.relative_to(REPO_ROOT)} has no `grep -q` assertion -- replay "
            f"produces logs but does not self-verify the claimed result"
        ]
    return []


def _receipt_area_claims(obj: object, key_path: str = "") -> list[tuple[str, float]]:
    """(key_path, value) for every numeric leaf under a key containing 'area'."""
    out: list[tuple[str, float]] = []
    if isinstance(obj, dict):
        for k, v in obj.items():
            out.extend(_receipt_area_claims(v, f"{key_path}.{k}" if key_path else str(k)))
    elif isinstance(obj, list):
        for i, v in enumerate(obj):
            out.extend(_receipt_area_claims(v, f"{key_path}[{i}]"))
    elif isinstance(obj, (int, float)) and not isinstance(obj, bool):
        # An area value, not a cell COUNT (a count under an area_receipts.* key
        # is not itself an area and is not carried in the synthesis area line).
        if _AREA_KEY.search(key_path) and not _CELL_KEY.search(key_path):
            out.append((key_path, float(obj)))
    return out


def _sha_bound_log_text(package: Path) -> str:
    """Concatenated text of every SHA-bound ``*.log`` in the package -- the
    pinned, hash-verified tool output the receipt's numbers must be PARSED
    FROM. Only SHA256SUMS-listed logs count, so an unbound log cannot launder
    a fabricated number."""
    listed = _sums_listed(package)
    chunks: list[str] = []
    for rel in sorted(listed):
        if rel.endswith(".log"):
            fp = package / rel
            if fp.is_file():
                chunks.append(fp.read_text(encoding="utf-8", errors="ignore"))
    return "\n".join(chunks)


def _verify_receipt_bound_to_logs(package: Path) -> list[str]:
    """Every AREA value the receipt CLAIMS must appear verbatim in a SHA-bound
    pinned log -- the receipt's numbers are PARSED FROM the hash-verified tool
    output, never self-asserted. An inflated/tampered area claim that no pinned
    log reproduces is caught. Correctness-only packets (no area claims) are a
    no-op by construction.

    Scope (structure, not execution): this proves the claimed number is PRESENT
    in a SHA-bound log; it does NOT re-run replay.sh. A forgery that fabricates
    BOTH the receipt value AND a matching, SHA256SUMS-listed log passes here --
    reproducibility ultimately rests on the auditor re-running replay.sh, which
    _verify_replay guarantees exists and self-checks. This gate catches drift,
    casual tampering, and self-certification; full forgery is caught by replay."""
    receipt = package / "receipt.json"
    if not receipt.is_file():
        return []
    try:
        data = json.loads(receipt.read_text(encoding="utf-8"))
    except json.JSONDecodeError:
        return []  # parse failure already flagged by _verify_receipt_json
    claims = _receipt_area_claims(data)
    if not claims:
        return []
    logtext = _sha_bound_log_text(package)
    problems: list[str] = []
    for key_path, value in claims:
        # Match the value at the precisions tool logs emit it (Yosys stat prints
        # 6 decimals; receipts round to 4). Require a decimal-anchored form so a
        # short area cannot spuriously match a longer number's prefix.
        forms = (f"{value:.6f}", f"{value:.4f}", f"{value:.1f}")
        if not any(form in logtext for form in forms):
            problems.append(
                f"{receipt.relative_to(REPO_ROOT)}: area claim {key_path}={value} does "
                f"not appear in any SHA-bound pinned log "
                f"(receipt self-certifies -- not parsed from the bound bytes)"
            )
    return problems


def verify(root: Path = ARTIFACT_ROOT) -> list[str]:
    # A capture-track fork (e.g. riscv-boom-athanor) legitimately has no proof
    # packages yet -- "no artifacts yet" is not a failure. Fail-closed means
    # "missing when expected," which is a separate content check; the export-safety
    # leak scan still runs over the whole committed tree regardless.
    if not root.is_dir():
        return []
    problems: list[str] = []
    # A proof package is a dir carrying a SHA256SUMS or a receipt.json. A capture
    # staging dir (e.g. generated_rtl_capture on the capture-track fork) has
    # neither and is not a proof package -> skip it. A dir with a receipt.json but
    # no SHA256SUMS is still a package and IS flagged by _verify_sums.
    packages = [
        p
        for p in sorted(root.iterdir())
        if p.is_dir() and ((p / "SHA256SUMS").is_file() or (p / "receipt.json").is_file())
    ]
    if not packages:
        return []
    for package in packages:
        problems.extend(_verify_sums(package))
        problems.extend(_verify_manifest_complete(package))
        problems.extend(_verify_receipt_json(package))
        problems.extend(_verify_replay(package))
        problems.extend(_verify_receipt_bound_to_logs(package))
        problems.extend(_verify_public_export_clean(package))
    return problems


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--artifact-root",
        type=Path,
        default=ARTIFACT_ROOT,
        help="artifact package root, default: athanor_artifacts",
    )
    args = parser.parse_args(argv)

    problems = verify(args.artifact_root)
    if problems:
        for problem in problems:
            print(f"FAIL: {problem}", file=sys.stderr)
        return 1
    print(f"OK: verified public receipts under {args.artifact_root.relative_to(REPO_ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
